OnePotatoTwoPotato/urls.py
from django.conf.urls import patterns, include, url
import OnePotatoTwoPotato.settings as settings

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # FIXME This actually maps two separate URLs to the same things - may be
    # problem with SEO here ...
    url(r'^/?', include('spuds.urls', namespace="spuds")),
    url(r'^spuds/', include('spuds.urls', namespace="spuds")),
    # url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

spuds/urls.py
from django.conf.urls import patterns, url

from spuds import views

urlpatterns = patterns('',
    url(r'^$', views.index, name="index"),
    url(r'^show/(?P<num>\d+)/$', views.show, name="show"),
)

spuds/models.py
from django.db import models

# Create your models here.

spuds/views.py
# Create your views here.

from django.shortcuts import render

def show(request, num):
    num = int(num)
    if num > 4:
        num = 4
    if num < 0:
        num = 0
    # FIXME: Really this data should be defined in the view, perhaps
    # using a custom template tag - see
    # https://docs.djangoproject.com/en/1.5/howto/custom-template-tags/#writing-custom-template-tags 
    img_fns = ['wafflecopter.png', 'potatosalad.png', 'hypnochips.png', 'spudnik.png']
    img_fns = img_fns[:num]
    return render(request, 'spuds/show.html', { 'img_fns': img_fns })

def index(request):
    return render(request, 'spuds/index.html')

spuds/templates/spuds/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <title>One potato, two potato &hellip;</title>

    <!-- Use some Google resources, not all are used here but will cache
         for upcoming pages -->
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,300' rel='stylesheet' type='text/css'>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'spuds/style.css' %}" />

  </head>
  <body>

    <div id="main-content">
        <h1>How many potatos?</h1>

        <ul id="choosenum">
            <li><a href="{% url 'spuds:show' 1 %}">One potato?</a></li>
            <li><a href="{% url 'spuds:show' 2 %}">Two potato?</a></li>
            <li><a href="{% url 'spuds:show' 3 %}">Three potato?</a></li>
            <li><a href="{% url 'spuds:show' 4 %}">Four?</a></li>
        </ul>
    </div>
  
  </body>
</html>

spuds/templates/spuds/show.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <title>One potato, two potato &hellip;</title>

    <!-- Use some Google resources -->
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,300' rel='stylesheet' type='text/css'>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'spuds/style.css' %}" />
    <script src="{% static 'spuds/js/place-potatos.js' %}"></script>


  </head>
  <body>

    <div id="arrow-container"><img src="{% static 'spuds/img/arrow-up.png' %}" /></div>
    <div id="prompt-container">
      <span class="lead-text">Django running on Windows Azure</span><br />
      <a href="https://bitbucket.org/brendanarnold/www-onepotatotwopotato">the code</a> by <a href="mailto:brendanarnold@gmail.com">brendanarnold@gmail.com</a><br />
    </div>

    <div id="spud-container">
    {% for fn in img_fns %}
      <div class="img-container">
        <img src="{% static 'spuds/img/' %}{{ fn }}" alt="A potato character" />
      </div>
    {% endfor %}
    </div>

  </body>
</html>